WIP draft of function-composition concept
exercism/julia pull request #821
Opened 2024-10-26 19:46 UTC by colinleach

I haven't looked closely at exercises to match this, but other tracks seem to use `high-school-sweetheart`.

2025-02-20 23:46 UTC, depial reviewed
lg2m

2025-02-20 23:54 UTC, colinleach commented
What's your preferred way forward? I could either add a (non-empty) `introduction.md`, or add `high-school-sweetheart` and copy the `introduction.md` from that. The latter option at least has the advantage that we'll know what a minimal Introduction looks like.

@depial, your choice.

2025-02-21 01:13 UTC, depial commented
I think the latter sounds great :)

2025-02-21 01:24 UTC, colinleach commented
I'll try to PR `high-school-sweetheart` in the next day or two, unless you're keen to do it yourself.

2025-02-21 01:56 UTC, depial commented
Great, I'll see if I can take a look at it as well. I'm hoping to get some of your work pushed through here since it's definitely quality. (Apologies for my recent absence, I hope to be around more now)

2025-02-21 02:26 UTC, colinleach commented
I've mostly been absent myself for the last several months. I had been making decent progress on the learning track, but then I got ill: mainly dermatology problems, but then side effects from the drugs treating it. I still spend quite a bit of time in medical waiting rooms, but I'll try to pick this up again and make progress.

I was most of the way through writing the `strings` concept when things went bad, so I hope to finish and PR that fairly soon.

2025-02-26 17:16 UTC, depial commented
I'm sorry to hear about your medical issues and wish you all the best with your recovery! If working on stuff here is too trying, definitely continue to take a break :)

I'll look at getting a PR with `high-school-sweetheart` opened today.

2025-02-26 17:36 UTC, colinleach commented
> I'm sorry to hear about your medical issues and wish you all the best with your recovery! 

Thank you. It's been a strange few months since my skin suddenly declared war on me, but I'm now getting treated. Yesterday I saw the dermatologist again, and she greeted me with a cheery "Good morning, my itchy friend". Fair enough, I also tease her a bit (30 years working in medical research changed my relationships with doctors: still respectful, not quietly deferential).

The initial treatments early October had a lot of side effects, but recent stuff is much better tolerated. I said in one post that the syllabus had stalled because my brain had stalled, which may have accidentally given the impression that I have mental health problems. Not true, it's just that I hadn't slept properly for several weeks. Though I can imagine the parents of newborn babies rolling their eyes and muttering _"tell me about it..."_.

2025-02-26 17:45 UTC, colinleach commented
I've now reversed strategy, and my immediate priority is to get early concepts/exercises fit to merge, so we can start building a WIP syllabus on the website. Writing the more advanced concepts was fun, and educational for me, but I now think I should postpone doing more of that.

There will be a hiatus mid-March, when a friend is flying out from England to stay with me for 10 days. I'll still be in fairly regular contact, but we'll be travelling around and I'll be less likely to write long-form content. Normal service will hopefully resume late-March.

2025-02-26 18:11 UTC, depial commented
My friend recently spent a couple of very itchy months with little sleep, so I've been told, in quite definite terms, it no fun at all.

I think your strategy seems reasonable. I also like creating exercises for more advanced topics, since I find them more self edifying, but I see this can only help so much and I'll have to bite the bullet and do some of the more "mundane" tasks as well. Luckily there's always nuggets of interest in anything if I keep my eyes open.

I may also be receiving guests in the middle of March, so maybe these periods could overlap. I don't think I will be traveling (much) though, so I should still be somewhat available if they don't.

2025-02-26 18:21 UTC, depial commented
I can't find `high-school-sweetheart` in `problem-specifications`... Am I looking in the wrong place, or do I have the wrong name for the exercise?

2025-02-26 18:53 UTC, colinleach commented
`problem-specifications` is only for Practice Exercises, where we aim for cross-language consistency. Tracks are free, and often required, to do their own thing with Concept Exercises. 

These tracks have `high-school-sweetheart` live: [crystal](https://github.com/exercism/crystal/tree/main/exercises/concept/high-school-sweetheart), elixir, gleam, csharp. I suggest you decide which one you prefer as a starting point, then steal it from their GH repo and adapt for Julia. Sorry, it's quite a manual process.

2025-02-26 19:13 UTC, depial commented
Gotcha!

Did you want to translate the `introduction.md`, for here (which I would copy), or should I have a go at it in the exercise (which you could copy for here)?

2025-02-26 19:39 UTC, colinleach commented
After trying a few approaches and having various discussions with Bethany, a good approach seems to be:
1. Copy the concept's `about.md` to the exercise's `introduction.md`.
2. Edit it right down, removing anything not directly relevant to solving the exercise.
3. Copy the shortened introduction to the Concept.

That way we achieve the twin goal of having a minimal introduction, and ensuring it is a subset of the `about.md`.

Of course, if you find the exercise forces you to add bits to the Introduction, those would need to be copied to the About so that it remains a strict superset.

I'm not sure I explained that very clearly. Does it make some sense?

2025-02-26 22:35 UTC, depial commented
I've opened a PR(https://github.com/exercism/julia/pull/830) with most of the necessary files for the concept exercise. However, I've left the `introduction.md` blank, to be filled in with `about.md` info. Also, I went ahead and translated the Crystal `instructions.md` and `hints.md` since they were quite simply done, but they will need to be changed to focus on function composition (rather than string methods).

2025-03-04 12:16 UTC, depial requested changes
This looks like it might be ready to merge, with the possible exception of the `links.json` file.

2025-03-04 12:16 UTC, depial commented on concepts.wip/function-composition/links.json
> +]
I'm not sure if this is an automatic process or a manual one. Do the other links used need to be added here? Is this a list that is used in `about.md` or `introduction.md` or the union?

2025-03-04 15:03 UTC, colinleach commented on concepts.wip/function-composition/links.json
> +]
I just looked up the [documentation](https://exercism.org/docs/building/tracks/concepts#h-file-links-json) again, because I never fully understood this JSON file. It's not related to the Markdown docs, they contain their own links. The idea seems to be to find a small number (maybe 1-3) of key references and list them here.

I always have trouble with this for Julia, because so much of the documentation is highly technical, and good 3rd-party websites are relatively rare. There are now some good textbooks (like [this](https://www.amazon.com/Julia-Second-Language-Erik-Engheim/dp/1617299715/ref=sr_1_11) and [this](https://www.amazon.com/Practical-Julia-Lee-Phillips/dp/1718502761/ref=sr_1_1) and [this](https://www.amazon.com/Julia-Data-Analysis-Bogumil-Kaminski/dp/1633439364/ref=sr_1_8)), but they're all pretty expensive. Linking to these is strongly discouraged, on a platform with so many students in low-income countries. We also try hard to avoid websites that require registration, even if it's free (though that's a guideline that can sometimes be broken).

I've been aware that links are an area of weakness, so if (more likely, _when_) you know of things I've missed, please add them and bring them to my attention.

Honestly, looking at much of the existing documentation is a strong motivation to create something more beginner-friendly (and free) on Exercism.

2025-03-04 15:26 UTC, depial approved these changes
lg2m

2025-03-04 15:26 UTC, merged

2025-03-04 15:28 UTC, depial commented on concepts.wip/function-composition/links.json
> +]
I had only noticed that file recently, so I appreciate the summary of what it's for. Cheers!